const fs=require('node:fs'),vm=require('node:vm'),ts=require('typescript'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const compile=f=>ts.transpileModule(fs.readFileSync(f,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText;
const gm={exports:{}};vm.runInNewContext(compile('lib/levels.ts'),{exports:gm.exports,module:gm,Date,Math,Array,JSON,Set,Number});const g=gm.exports;
const disk=new Map(),localStorage={getItem:k=>disk.get(k)||null,setItem:(k,v)=>disk.set(k,v)};let server=g.parseLevelProgress(JSON.stringify({coins:500})),revision=0,lose=true,requests=0;const receipts=new Set();
const fetch=async(url,opts)=>{const b=JSON.parse(opts.body);if(b.action==='open')return{ok:true,status:200,json:async()=>({progress:server,revision,account:'123'})};requests++;if(receipts.has(b.commandId))return{ok:true,status:200,json:async()=>({progress:server,revision})};if(b.revision!==revision)return{ok:false,status:409,json:async()=>({progress:server,revision})};server=g.applyCommand(server,b.command);revision++;receipts.add(b.commandId);if(lose){lose=false;return new Promise(()=>{});}return{ok:true,status:200,json:async()=>({progress:server,revision})};};
function store(){const m={exports:{}};vm.runInNewContext(compile('lib/progress-store.ts'),{module:m,exports:m.exports,require:n=>n==='react'?{useSyncExternalStore(){}}:g,localStorage,fetch,crypto,AbortSignal,URLSearchParams,Date,Math,Array,JSON,Set,Number,location:{origin:'https://example.test'}});return m.exports;}
const flush=()=>new Promise(r=>setImmediate(r));
(async()=>{const a=store();await a.initializeProgress('user='+encodeURIComponent(JSON.stringify({id:123})));a.dispatchProgress({type:'exchange'});await flush();assert.equal(server.coins,400);assert.equal(server.blu,1);assert.equal(JSON.parse(disk.get('blu_account_123_outbox')).length,1);
const b=store();await b.initializeProgress('user='+encodeURIComponent(JSON.stringify({id:123})));await flush();await flush();assert.equal(b.getProgress().coins,400);assert.equal(b.getProgress().blu,1);assert.equal(JSON.parse(disk.get('blu_account_123_outbox')).length,0);assert.equal(b.getSyncStatus(),'cloud');assert.equal(requests,2);console.log('PASS: interrupted response, persistent outbox replay, stable command ID, no duplicate conversion');})();
