const fs=require('node:fs'),vm=require('node:vm'),ts=require('typescript'),assert=require('node:assert/strict');
const out=ts.transpileModule(fs.readFileSync('lib/levels.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText;const mod={exports:{}};vm.runInNewContext(out,{exports:mod.exports,module:mod,require:n=>require("./i18n-helper.cjs"),Date,Set,Number,JSON,Array,Math});const g=mod.exports;let p=g.parseLevelProgress(null);
assert.equal(g.applyCommand(p,{type:'finish',id:6}),p);assert.equal(g.applyCommand(p,{type:'collect',id:3,index:0}),p);
for(const l of g.LEVELS){for(let i=0;i<l.required;i++)p=g.applyCommand(p,{type:'collect',id:l.id,index:i});p=g.applyCommand(p,{type:'finish',id:l.id});assert.equal(p.completed.length,l.id);const after=g.applyCommand(p,{type:'finish',id:l.id});assert.equal(after.coins,p.coins);}
assert.equal(p.coins,1230);const bought=g.applyCommand(p,{type:'buy',id:'shoes'});assert.equal(bought.coins,1080);assert.equal(g.applyCommand(bought,{type:'buy',id:'shoes'}),bought);assert.equal(g.applyCommand(p,{type:'equip',id:'gold'}),p);
p=g.applyCommand(bought,{type:'buy',id:'gold'});p=g.applyCommand(p,{type:'equip',id:'gold'});assert.equal(p.skin,'gold');p=g.applyCommand(p,{type:'exchange'});assert.equal(p.blu,1);assert.equal(p.coins,630);p=g.applyCommand(p,{type:'dash'});assert.equal(p.coins,510);assert.equal(p.dashLevel,1);
let daily=g.applyCommand(p,{type:'daily'},Date.parse('2026-09-29'));assert.equal(daily.coins,530);assert.equal(g.applyCommand(daily,{type:'daily'},Date.parse('2026-09-29')),daily);daily=g.applyCommand(daily,{type:'daily'},Date.parse('2026-09-30'));assert.equal(daily.coins,560);
let run=g.applyCommand(p,{type:'run-start'},100000);assert.equal(g.applyCommand(run,{type:'run-finish',bolts:20},110000),run);run=g.applyCommand(run,{type:'run-finish',bolts:20},125000);assert.equal(run.coins,550);assert.equal(run.runs,1);assert.equal(g.applyCommand(run,{type:'run-finish',bolts:20},130000),run);assert.equal(g.applyCommand(run,{type:'run-start'},135000),run);assert.ok(g.applyCommand(run,{type:'run-start'},186000).runStarted);
const old=g.parseLevelProgress(JSON.stringify({version:2,restored:true,metroDone:true,coins:250,blu:2,dashLevel:1}));assert.equal(old.completed.length,2);assert.equal(g.unlockedLevel(old),3);assert.equal(old.coins,250);assert.equal(g.parseLevelProgress(JSON.stringify(p)).skin,'gold');
console.log('PASS: six missions, rewards once, prerequisites, equipment, currency, dash, daily, run duration/cooldown, save migration');

assert.equal(g.applyCommand(g.parseLevelProgress(null),{type:'next-city'}).cityLevel,1);
const city2=g.applyCommand(p,{type:'next-city',cityLevel:1});assert.equal(city2.cityLevel,2);assert.equal(city2.completed.length,0);assert.equal(city2.restored,false);assert.equal(city2.skin,'gold');assert.equal(city2.coins,p.coins);assert.equal(city2.blu,p.blu);assert.equal(city2.dashLevel,p.dashLevel);assert.ok(city2.inventory.includes('shoes'));assert.equal(g.applyCommand(city2,{type:'collect',id:1,index:0,cityLevel:1}),city2);
let second=city2;for(const l of g.cityMissions(2)){for(let i=0;i<l.required;i++)second=g.applyCommand(second,{type:'collect',id:l.id,index:i,cityLevel:2});second=g.applyCommand(second,{type:'finish',id:l.id,cityLevel:2});assert.equal(second.restored,l.id===6);}assert.equal(second.coins,p.coins+1230);assert.equal(g.parseLevelProgress(JSON.stringify(second)).cityLevel,2);assert.ok(g.cityScale(2)>g.cityScale(1));
assert.equal(g.applyCommand({...city2,coins:500},{type:'buy',id:'neon'}).skin,'neon');
console.log('PASS: city transition, six missions per city, old-city replay rejected, balances/equipment preserved, skin auto-equipped');
