// CPU scene integration: real Three geometry/mission loop, mocked GPU and input.
const fs=require('node:fs'),vm=require('node:vm'),ts=require('typescript'),assert=require('node:assert/strict'),THREE=require('three');
function load(file,req,globals={}){const out=ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020,jsx:ts.JsxEmit.ReactJSX}}).outputText;const mod={exports:{}};vm.runInNewContext(out,{exports:mod.exports,module:mod,require:req,...globals});return mod.exports;}
const g=load('lib/levels.ts',require,{Date,Math,Array,Set,JSON,Number});let progress=g.parseLevelProgress(null),hud,effects=[],refs=[],clock=0,frame;
const element=()=>({style:{},classList:{remove(){},add(){}},append(){},remove(){},addEventListener(){},offsetWidth:1,clientWidth:390,clientHeight:844});
const react={useRef(v){const ref={current:v===null?element():v};refs.push(ref);return ref;},useState(v){return[v,next=>{if(next&&typeof next==='object'&&'level'in next)hud=next;}];},useEffect(fn){effects.push(fn);}};
class Renderer{constructor(){this.domElement=element();}setPixelRatio(){}setSize(){}render(){}dispose(){}}
class Rig{constructor(){this.root=new THREE.Group();}update(){}setEnergy(){}setEquipment(){}jump(){}land(){}dispose(){}}
let rejectFinish=false;
const store={getProgress:()=>progress,getSyncStatus:()=> 'device',dispatchProgress:c=>(progress=rejectFinish&&c.type==='finish'?progress:g.applyCommand(progress,c,clock)),checkpointProgress:s=>{for(const l of g.LEVELS){const flags=l.id===1?s.cells:l.id===2?s.metro:s.objectives[l.id];flags.forEach((v,i)=>{if(v)progress=g.applyCommand(progress,{type:'collect',id:l.id,index:i},clock);});if(l.id===1?s.restored:l.id===2?s.metroDone:s.completed.includes(l.id))progress=g.applyCommand(progress,{type:'finish',id:l.id},clock);}return progress;}};
let source=fs.readFileSync('app/components/PlayableCity.tsx','utf8');source=source.replace('const key = new Set<string>();','globalThis.sceneTest={state,input:input.current};const key = new Set<string>();');
const out=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020,jsx:ts.JsxEmit.ReactJSX}}).outputText;const mod={exports:{}};const ctx={exports:mod.exports,module:mod,require:n=>n==='react'?react:n==='three'?new Proxy(THREE,{get:(o,k)=>k==='WebGLRenderer'?Renderer:o[k]}):n==='./BluRig'?{BluRig:Rig,toon:c=>new THREE.MeshToonMaterial({color:c})}:n.includes('progress-store')?store:n.includes('levels')?g:require(n),document:{hidden:false,createElement:element},window:{addEventListener(){},removeEventListener(){}},navigator:{vibrate(){}},localStorage:{getItem(){return null;}},performance:{now:()=>clock},devicePixelRatio:1,ResizeObserver:class{constructor(fn){this.fn=fn;}observe(){this.fn();}disconnect(){}},requestAnimationFrame:fn=>(frame=fn,1),cancelAnimationFrame(){},Date,Math,Array,Set,JSON,Number};vm.createContext(ctx);vm.runInContext(out,ctx);mod.exports.default({lang:'en',onMenu(){},onReward(){},serverRestored:false});effects[0]();const scene=ctx.sceneTest;
const tick=(n=1)=>{for(let i=0;i<n;i++){clock+=40;frame();}};scene.input.start=true;tick();
const visit=(x,z,y=0)=>{scene.state.pos.set(x,y,z);scene.state.vy=0;tick(2);};
for(const[x,z]of[[-11,-8],[12,-23],[-4,-43]])visit(x,z);assert.equal(hud.cells,3);visit(0,-35);scene.input.charge=true;tick(50);scene.input.charge=false;assert.equal(progress.completed.length,1);assert.equal(progress.coins,100);
scene.input.next=true;tick();for(const[x,z]of[[-13,-44],[11,-49]])visit(x,z);visit(-9,-50);scene.input.charge=true;tick(50);scene.input.charge=false;assert.equal(progress.completed.length,2);
scene.input.next=true;tick();
// Walk mission 3 from the metro exit, rather than teleporting through scenery.
const walkTo=(x,z)=>{for(let n=0;n<1500;n++){const dx=x-scene.state.pos.x,dz=z-scene.state.pos.z;if(Math.hypot(dx,dz)<.35)break;scene.input.x=Math.abs(dx)>.2?Math.sign(dx):0;scene.input.y=Math.abs(dz)>.2?Math.sign(dz):0;tick();}scene.input.x=scene.input.y=0;tick(5);assert.ok(Math.hypot(x-scene.state.pos.x,z-scene.state.pos.z)<1,'Reach mission target using movement');};
walkTo(17,-49);for(const[x,z]of[[17,-42],[17,-25],[17,-16]]){const before=progress.objectives[3].filter(Boolean).length;walkTo(x,z);assert.equal(progress.objectives[3].filter(Boolean).length,before,"Pickup alone is not delivery");assert.equal(hud.carrying,true);walkTo(17,-31);assert.equal(progress.objectives[3].filter(Boolean).length,before+1);}assert.equal(hud.extraGot,3);walkTo(17,-31);assert.equal(hud.nearby,true);rejectFinish=true;scene.input.charge=true;tick(50);assert.equal(hud.levelDone,false);assert.equal(hud.celebrating,false,'Rejected completion must not display victory');rejectFinish=false;tick(50);scene.input.charge=false;assert.equal(progress.completed.length,3);assert.ok(hud.completed.includes(3),'Pause status includes mission 3');

scene.input.next=true;tick();visit(8,-10);scene.input.y=-1;for(let n=0;n<180&&scene.state.pos.z>-40;n++)tick();scene.input.y=0;tick(5);assert.ok(scene.state.pos.z < -38,'Rooftop route can be walked with actual input');assert.equal(hud.extraGot,3);scene.input.x=-1;tick(11);scene.input.x=0;tick(5);assert.ok(scene.state.pos.y>=2.9,'Can reach roof terminal without teleporting');scene.input.charge=true;tick(50);scene.input.charge=false;assert.equal(progress.completed.length,4);
scene.input.next=true;tick();walkTo(17,-41);walkTo(14,-47);walkTo(29,-50);assert.equal(hud.escortReady,false,"Escort cannot finish while robot is at pickup");walkTo(24,-52);tick(100);scene.input.charge=true;tick(50);scene.input.charge=false;assert.equal(progress.completed.length,5);
scene.input.next=true;tick();walkTo(24,-60);walkTo(-8,-60);for(const[x,z]of[[-8,-73],[12,-79],[27,-89]]){walkTo(x,z);tick(5);assert.equal(hud.nodeReady,true);const before=progress.objectives[6].filter(Boolean).length;assert.equal(hud.extraGot,before,"Power nodes require charge, not proximity");scene.input.charge=true;tick(50);scene.input.charge=false;assert.equal(progress.objectives[6].filter(Boolean).length,before+1);}walkTo(12,-63);scene.input.charge=true;tick(50);scene.input.charge=false;assert.equal(progress.completed.length,6);assert.equal(progress.coins,1230);scene.input.next=true;tick();assert.equal(progress.cityLevel,2);assert.equal(progress.completed.length,0);
console.log('PASS: actual scene loop completes missions 1–6 with correct checkpoints/rewards, roof collectibles, escort and next transitions');

const actualRig=load('app/components/BluRig.ts',require,{document:{createElement:()=>({getContext:()=>null})}}).BluRig;
const rig=new actualRig();rig.setEquipment({skin:'gold',inventory:['shoes','gloves','battery','gold']});const colors=new Set();rig.root.traverse(o=>{if(o.isMesh&&!Array.isArray(o.material)&&o.material.color)colors.add(o.material.color.getHex());});assert.ok(colors.has(0xffc84a));assert.ok(colors.has(0xff664f));assert.ok(colors.has(0xffcf45));rig.dispose();console.log('PASS: purchased skin, shoes and gloves color actual character mesh materials');

// Run mode must finish even when the story is waiting for the escort mission.
progress=g.parseLevelProgress(null);for(const id of [1,2,3,4]){for(let index=0;index<g.LEVELS[id-1].required;index++)progress=g.applyCommand(progress,{type:'collect',id,index},clock);progress=g.applyCommand(progress,{type:'finish',id},clock);}
clock=Math.max(clock,60001);effects=[];refs=[];mod.exports.default({lang:'en',onMenu(){},onReward(){},serverRestored:false,challenge:true});effects[0]();const run=ctx.sceneTest;run.input.start=true;tick();run.state.bolts=25;tick(550);run.state.pos.set(0,0,-50);run.state.vy=0;tick(5);assert.equal(hud.nearby,true);run.input.charge=true;tick(50);run.input.charge=false;assert.equal(hud.runDone,true);assert.equal(progress.runs,1);assert.equal(progress.completed.join(','),'1,2,3,4');assert.equal(progress.coins,690);tick(100);assert.equal(progress.runs,1);console.log('PASS: energy circuit awards once without completing or depending on escort mission');

let previewEffects=[],previewGpu=0;const previewReact={useRef:()=>({current:element()}),useState:v=>[v,()=>{}],useEffect:fn=>previewEffects.push(fn)};
const Preview=load('app/components/WardrobePreview.tsx',n=>n==='react'?previewReact:n==='three'?new Proxy(THREE,{get:(o,k)=>k==='WebGLRenderer'?class{constructor(){previewGpu++;throw Error('GPU unavailable');}}:o[k]}):n==='./BluRig'?{BluRig:Rig}:n.includes('progress-store')?store:require(n),{window:{matchMedia:()=>({matches:true})}}).default;const preview=Preview();assert.equal(preview.props.children[0].type,'img');assert.equal(previewGpu,0,'Touch devices must not create a wardrobe WebGL context');console.log('PASS: mobile wardrobe avoids a second GPU context');
