// CPU scene integration: real Three geometry/mission loop, mocked GPU and input.
const fs=require('node:fs'),vm=require('node:vm'),ts=require('typescript'),assert=require('node:assert/strict'),THREE=require('three');
function load(file,req,globals={}){const out=ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020,jsx:ts.JsxEmit.ReactJSX}}).outputText;const mod={exports:{}};vm.runInNewContext(out,{exports:mod.exports,module:mod,require:req,...globals});return mod.exports;}
const g=load('lib/levels.ts',require,{Date,Math,Array,Set,JSON,Number});let progress=g.parseLevelProgress(null),hud,effects=[],refs=[],clock=0,frame;
const element=()=>({style:{},classList:{remove(){},add(){}},append(){},remove(){},addEventListener(){},offsetWidth:1,clientWidth:390,clientHeight:844});
const react={useRef(v){const ref={current:v===null?element():v};refs.push(ref);return ref;},useState(v){return[v,next=>{if(next&&typeof next==='object'&&'level'in next)hud=next;}];},useEffect(fn){effects.push(fn);}};
class Renderer{constructor(){this.domElement=element();}setPixelRatio(){}setSize(){}render(){}dispose(){}}
class Rig{constructor(){this.root=new THREE.Group();}update(){}setEnergy(){}setEquipment(){}jump(){}land(){}dispose(){}}
const store={getProgress:()=>progress,getSyncStatus:()=> 'device',dispatchProgress:c=>(progress=g.applyCommand(progress,c,clock)),checkpointProgress:s=>{for(const l of g.LEVELS){const flags=l.id===1?s.cells:l.id===2?s.metro:s.objectives[l.id];flags.forEach((v,i)=>{if(v)progress=g.applyCommand(progress,{type:'collect',id:l.id,index:i},clock);});if(l.id===1?s.restored:l.id===2?s.metroDone:s.completed.includes(l.id))progress=g.applyCommand(progress,{type:'finish',id:l.id},clock);}return progress;}};
let source=fs.readFileSync('app/components/PlayableCity.tsx','utf8');source=source.replace('const key = new Set<string>();','globalThis.sceneTest={state,input:input.current};const key = new Set<string>();');
const out=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020,jsx:ts.JsxEmit.ReactJSX}}).outputText;const mod={exports:{}};const ctx={exports:mod.exports,module:mod,require:n=>n==='react'?react:n==='three'?new Proxy(THREE,{get:(o,k)=>k==='WebGLRenderer'?Renderer:o[k]}):n==='./BluRig'?{BluRig:Rig,toon:c=>new THREE.MeshToonMaterial({color:c})}:n.includes('progress-store')?store:n.includes('levels')?g:require(n),document:{hidden:false,createElement:element},window:{addEventListener(){},removeEventListener(){}},navigator:{vibrate(){}},localStorage:{getItem(){return null;}},performance:{now:()=>clock},devicePixelRatio:1,ResizeObserver:class{constructor(fn){this.fn=fn;}observe(){this.fn();}disconnect(){}},requestAnimationFrame:fn=>(frame=fn,1),cancelAnimationFrame(){},Date,Math,Array,Set,JSON,Number};vm.createContext(ctx);vm.runInContext(out,ctx);mod.exports.default({lang:'en',onMenu(){},onReward(){},serverRestored:false});effects[0]();const scene=ctx.sceneTest;
const tick=(n=1)=>{for(let i=0;i<n;i++){clock+=40;frame();}};scene.input.start=true;tick();
const visit=(x,z,y=0)=>{scene.state.pos.set(x,y,z);scene.state.vy=0;tick(2);};
for(const[x,z]of[[-11,-8],[12,-23],[-4,-43]])visit(x,z);assert.equal(hud.cells,3);visit(0,-35);scene.input.charge=true;tick(50);scene.input.charge=false;assert.equal(progress.completed.length,1);assert.equal(progress.coins,100);
scene.input.next=true;tick();for(const[x,z]of[[-13,-44],[11,-49]])visit(x,z);visit(-9,-50);scene.input.charge=true;tick(50);scene.input.charge=false;assert.equal(progress.completed.length,2);
scene.input.next=true;tick();for(const[x,z]of[[17,-16],[28,-23],[21,-40]])visit(x,z);visit(27,-30);scene.input.charge=true;tick(50);scene.input.charge=false;assert.equal(progress.completed.length,3);
scene.input.next=true;tick();visit(8,-18,3);visit(8,-26,4);visit(8,-35,4);assert.equal(hud.extraGot,3);visit(4,-41,3);scene.input.charge=true;tick(50);scene.input.charge=false;assert.equal(progress.completed.length,4);
scene.input.next=true;tick();visit(14,-47);visit(29,-50);visit(24,-52);tick(100);scene.input.charge=true;tick(50);scene.input.charge=false;assert.equal(progress.completed.length,5);
scene.input.next=true;tick();for(const[x,z]of[[-8,-73],[12,-79],[27,-89]])visit(x,z);visit(12,-63);scene.input.charge=true;tick(50);scene.input.charge=false;assert.equal(progress.completed.length,6);assert.equal(progress.coins,1230);
console.log('PASS: actual scene loop completes missions 1–6 with correct checkpoints/rewards, roof collectibles, escort and next transitions');
