'use client';
import Image from 'next/image';
import { useEffect, useState } from 'react';
type Lang='en'|'he'|'ar';
type Player={sparks:number;charge:number;level:number;district:number;missions:number;lastCharge:string|null;lastMission:string|null;referrals:number};
type Tg={initData:string;initDataUnsafe?:{user?:{id:number;first_name?:string;language_code?:string}};ready:()=>void;expand:()=>void;HapticFeedback?:{impactOccurred:(s:string)=>void}};
declare global {interface Window {Telegram?:{WebApp?:Tg}}}
const initial:Player={sparks:50,charge:70,level:1,district:1,missions:0,lastCharge:null,lastMission:null,referrals:0};
const dict={
 en:{subtitle:'CITY OF ENERGY',tagline:'Charge up. Light the city.',demo:'Preview mode · progress saved in this browser',online:'Connected to Telegram',hello:'Welcome back',city:'City power',district:'District',lit:'lit',sparks:'Sparks',charge:'Charge',level:'BLU level',missions:'Missions',tabPlay:'Play',tabCity:'City',tabFriends:'Friends',missionTitle:'Energy run',missionDesc:'Send BLU on a quick mission. Costs 10 charge.',missionButton:'Run mission',reward:'Earn',rechargeTitle:'Recharge station',rechargeDesc:'Restore 30 charge every 3 hours.',rechargeButton:'Collect charge',upgradeTitle:'Power up BLU',upgradeDesc:'Earn 5 more sparks per mission for each level.',upgradeButton:'Upgrade',districtTitle:'Light a new district',districtDesc:'Bring the city back to life, one district at a time.',districtButton:'Unlock district',friendTitle:'Power is better together',friendDesc:'Invite a friend. When they complete 3 missions, you earn 50 sparks.',friendButton:'Invite friend',friendCopy:'Copy invite link',referrals:'Friends invited',notReady:'Your invite link appears inside Telegram after connecting the bot.',low_charge:'Not enough charge. Recharge and try again.',low_sparks:'Not enough sparks yet.',cooldown:'Come back when the timer is over.',max_level:'Maximum level reached.',max_district:'The whole city is lit!',success:'Done! BLU is getting stronger.',offline:'Could not connect. Try again.',loading:'Connecting...',notConfigured:'Connect the bot and database to save progress for all players.',notice:'Game sparks have no cash value and cannot be withdrawn.',locked:'Next unlock',now:'Ready',copy:'Copied!',play:'PLAY NOW'},
 he:{subtitle:'עיר האנרגיה',tagline:'טוענים את BLU. מאירים את העיר.',demo:'מצב הדגמה · ההתקדמות נשמרת בדפדפן',online:'מחובר לטלגרם',hello:'טוב שחזרת',city:'אנרגיית העיר',district:'אזור',lit:'מואר',sparks:'ניצוצות',charge:'טעינה',level:'רמת BLU',missions:'משימות',tabPlay:'משחק',tabCity:'העיר',tabFriends:'חברים',missionTitle:'משימת אנרגיה',missionDesc:'שלח את BLU למשימה קצרה. עולה 10 טעינה.',missionButton:'צא למשימה',reward:'פרס',rechargeTitle:'תחנת טעינה',rechargeDesc:'ממלאים 30 טעינה כל 3 שעות.',rechargeButton:'אסוף טעינה',upgradeTitle:'שדרג את BLU',upgradeDesc:'כל רמה מוסיפה 5 ניצוצות לכל משימה.',upgradeButton:'שדרג',districtTitle:'האר אזור חדש',districtDesc:'מחזירים את האור לעיר, אזור אחר אזור.',districtButton:'פתח אזור',friendTitle:'יותר אנרגיה ביחד',friendDesc:'הזמן חבר. אחרי שישלים 3 משימות תקבל 50 ניצוצות.',friendButton:'הזמן חבר',friendCopy:'העתק קישור',referrals:'חברים שהוזמנו',notReady:'קישור ההזמנה יופיע לאחר חיבור הבוט בטלגרם.',low_charge:'אין מספיק טעינה. טען את BLU ונסה שוב.',low_sparks:'עדיין אין מספיק ניצוצות.',cooldown:'אפשר לחזור כשהטיימר יסתיים.',max_level:'הגעת לרמה המרבית.',max_district:'כל העיר מוארת!',success:'בוצע! BLU מתחזק.',offline:'החיבור נכשל. נסה שוב.',loading:'מתחבר...',notConfigured:'חבר בוט ומסד נתונים כדי לשמור התקדמות לכל השחקנים.',notice:'לניצוצות המשחק אין ערך כספי ואי אפשר למשוך אותם.',locked:'פתיחה הבאה',now:'מוכן',copy:'הועתק!',play:'שחק עכשיו'},
 ar:{subtitle:'مدينة الطاقة',tagline:'اشحن BLU. نوّر المدينة.',demo:'وضع تجريبي · التقدم محفوظ في هذا المتصفح',online:'متصل بتليجرام',hello:'أهلًا بعودتك',city:'طاقة المدينة',district:'منطقة',lit:'مضاءة',sparks:'شرارات',charge:'الشحن',level:'مستوى BLU',missions:'المهام',tabPlay:'اللعب',tabCity:'المدينة',tabFriends:'الأصدقاء',missionTitle:'مهمة الطاقة',missionDesc:'أرسل BLU في مهمة قصيرة. تكلف 10 شحنات.',missionButton:'ابدأ المهمة',reward:'المكافأة',rechargeTitle:'محطة الشحن',rechargeDesc:'استعد 30 شحنة كل 3 ساعات.',rechargeButton:'اجمع الشحن',upgradeTitle:'طوّر BLU',upgradeDesc:'كل مستوى يزيد 5 شرارات لكل مهمة.',upgradeButton:'طوّر',districtTitle:'أنر منطقة جديدة',districtDesc:'رجّع النور للمدينة، منطقة بعد منطقة.',districtButton:'افتح المنطقة',friendTitle:'الطاقة أحلى مع الأصحاب',friendDesc:'ادعُ صديقًا. بعد إكمال 3 مهام تحصل على 50 شرارة.',friendButton:'ادعُ صديقًا',friendCopy:'انسخ الرابط',referrals:'الأصدقاء المدعوون',notReady:'يظهر رابط الدعوة بعد ربط البوت في تليجرام.',low_charge:'الشحن غير كافٍ. اشحن BLU وحاول ثانية.',low_sparks:'الشرارات غير كافية بعد.',cooldown:'ارجع بعد انتهاء المؤقت.',max_level:'وصلت للمستوى الأعلى.',max_district:'المدينة كلها مضاءة!',success:'تم! BLU صار أقوى.',offline:'فشل الاتصال. حاول مرة ثانية.',loading:'جارٍ الاتصال...',notConfigured:'اربط البوت وقاعدة البيانات لحفظ تقدم اللاعبين.',notice:'شرارات اللعبة ليس لها قيمة نقدية ولا يمكن سحبها.',locked:'الفتح القادم',now:'جاهز',copy:'تم النسخ!',play:'العب الآن'}
} as const;
function remaining(time:string|null,hours:number,tick:number){if(!time)return 0;return Math.max(0,Math.ceil((new Date(time).getTime()+hours*3600000-tick)/60000));}
export default function Home(){
 const [lang,setLang]=useState<Lang>('en'); const [player,setPlayer]=useState<Player>(initial);const [tab,setTab]=useState<'play'|'city'|'friends'>('play');const [mode,setMode]=useState<'loading'|'live'|'demo'>('loading');const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');const [tick,setTick]=useState(0);const [telegram,setTelegram]=useState<Tg|null>(null);
 const t=dict[lang];const rtl=lang!=='en';const [botName,setBotName]=useState('');
 useEffect(()=>{const tg=window.Telegram?.WebApp||null;setTelegram(tg);tg?.ready();tg?.expand();const pref=tg?.initDataUnsafe?.user?.language_code||navigator.language||'en';setLang(pref.startsWith('he')?'he':pref.startsWith('ar')?'ar':'en');setBotName(process.env.NEXT_PUBLIC_TELEGRAM_BOT_USERNAME||'BluCityGame_bot');if(tg?.initData){fetch('/api/game',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({initData:tg.initData,action:'open'})}).then(async r=>{if(!r.ok)throw Error();const d=await r.json();setPlayer(d.player);setMode('live')}).catch(()=>setMode('demo'))}else{try{const saved=localStorage.getItem('blu_demo');if(saved)setPlayer(JSON.parse(saved))}catch{}setMode('demo')}const timer=setInterval(()=>setTick(Date.now()),30000);setTick(Date.now());return()=>clearInterval(timer)},[]);
 async function act(action:'mission'|'charge'|'upgrade'|'district'){
  if(busy)return;setBusy(true);setMessage('');let response:{message:string;player:Player}|null=null;
  try{if(mode==='live'&&telegram?.initData){const r=await fetch('/api/game',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({initData:telegram.initData,action})});if(!r.ok)throw Error();response=await r.json()}else{const p={...player};let code='ok';const now=Date.now();if(action==='charge'){if(remaining(p.lastCharge,3,now))code='cooldown';else{p.charge=Math.min(100,p.charge+30);p.lastCharge=new Date(now).toISOString()}}if(action==='mission'){if(p.charge<10)code='low_charge';else if(remaining(p.lastMission,1,now))code='cooldown';else{p.charge-=10;p.sparks+=30+5*(p.level-1);p.missions++;p.lastMission=new Date(now).toISOString()}}if(action==='upgrade'){if(p.sparks<80*p.level)code='low_sparks';else if(p.level>=100)code='max_level';else{p.sparks-=80*p.level;p.level++}}if(action==='district'){if(p.sparks<100*p.district)code='low_sparks';else if(p.district>=20)code='max_district';else{p.sparks-=100*p.district;p.district++}}response={message:code,player:p};if(code==='ok')localStorage.setItem('blu_demo',JSON.stringify(p))}
   if(response){setPlayer(response.player);setMessage(response.message==='ok'?t.success:t[response.message as keyof typeof t]||response.message);if(response.message==='ok')telegram?.HapticFeedback?.impactOccurred('light')}
  }catch{setMessage(t.offline)}finally{setBusy(false);setTick(Date.now())}
 }
 const chargeWait=remaining(player.lastCharge,3,tick), missionWait=remaining(player.lastMission,1,tick);
 const invite=botName&&telegram?.initDataUnsafe?.user?.id?`https://t.me/${botName.replace('@','')}?startapp=ref_${telegram.initDataUnsafe.user.id}`:'';
 async function share(){if(!invite){setMessage(t.notReady);return}if(navigator.share)await navigator.share({title:'BLU',url:invite}).catch(()=>{});else{await navigator.clipboard.writeText(invite);setMessage(t.copy)}}
 return <main lang={lang} dir={rtl?'rtl':'ltr'} className="shell"><div className="ambient a"/><div className="ambient b"/><header><div className="brand"><span className="brandbolt">ϟ</span><strong>BLU</strong><span className="brand-sub">{t.subtitle}</span></div><select aria-label="Language" value={lang} onChange={e=>setLang(e.target.value as Lang)}><option value="en">🇬🇧 EN</option><option value="he">🇮🇱 עברית</option><option value="ar">العربية</option></select></header>
 <div className="status"><span className={mode==='live'?'dot live':'dot'}/>{mode==='loading'?t.loading:mode==='live'?t.online:t.demo}</div>
 <section className="hero"><div className="hero-copy"><p className="eyebrow">⚡ {t.hello}</p><h1>{t.tagline}</h1><div className="level-pill">✦ {t.level} {player.level}</div></div><div className="character"><div className="glow"/><Image src="/blu.webp" alt="BLU, the blue battery character" width={390} height={390} priority/></div></section>
 <div className="stats"><div className="stat"><span>✦ {t.sparks}</span><strong>{player.sparks}</strong></div><div className="stat"><span>ϟ {t.charge}</span><strong>{player.charge}<small>/100</small></strong></div><div className="stat"><span>◈ {t.district}</span><strong>{player.district}<small>/20</small></strong></div></div>
 <nav><button className={tab==='play'?'active':''} onClick={()=>setTab('play')}>⚡ {t.tabPlay}</button><button className={tab==='city'?'active':''} onClick={()=>setTab('city')}>◈ {t.tabCity}</button><button className={tab==='friends'?'active':''} onClick={()=>setTab('friends')}>☻ {t.tabFriends}</button></nav>
 {tab==='play'&&<section className="cards"><div className="card feature"><div className="icon orange">⚡</div><div><h2>{t.missionTitle}</h2><p>{t.missionDesc}</p><small>✦ {t.reward} {30+5*(player.level-1)} {t.sparks}</small></div><button disabled={busy||!!missionWait} onClick={()=>act('mission')}>{missionWait?`${missionWait}m`:t.missionButton}</button></div><div className="card"><div className="icon cyan">ϟ</div><div><h2>{t.rechargeTitle}</h2><p>{t.rechargeDesc}</p></div><button disabled={busy||!!chargeWait} onClick={()=>act('charge')}>{chargeWait?`${chargeWait}m`:t.rechargeButton}</button></div><div className="card"><div className="icon violet">✦</div><div><h2>{t.upgradeTitle}</h2><p>{t.upgradeDesc}</p></div><button disabled={busy} onClick={()=>act('upgrade')}>{t.upgradeButton} · {80*player.level} ✦</button></div></section>}
 {tab==='city'&&<section className="cards"><div className="city-grid">{Array.from({length:6},(_,i)=><div key={i} className={i<player.district?'tile lit':'tile'}><span>{i<player.district?'✦':'◇'}</span><small>{t.district} {i+1}</small></div>)}</div><div className="card"><div className="icon cyan">◈</div><div><h2>{t.districtTitle}</h2><p>{t.districtDesc}</p></div><button disabled={busy||player.district>=20} onClick={()=>act('district')}>{t.districtButton} · {100*player.district} ✦</button></div></section>}
 {tab==='friends'&&<section className="cards"><div className="card"><div className="icon violet">☻</div><div><h2>{t.friendTitle}</h2><p>{t.friendDesc}</p><small>{t.referrals}: {player.referrals}</small></div><button onClick={share}>{t.friendButton}</button>{invite&&<button className="ghost" onClick={()=>{navigator.clipboard.writeText(invite);setMessage(t.copy)}}>{t.friendCopy}</button>}</div></section>}
 {message&&<div className="toast" role="status" onClick={()=>setMessage('')}>{message}</div>}<footer>{t.notice}</footer></main>
}
