import {NextRequest,NextResponse} from 'next/server';
import {timingSafeEqual} from 'node:crypto';
import {database} from '@/lib/game-server';
import {paymentsEnabled} from '@/lib/coin-packs';
export const runtime='nodejs';
async function bot(method:string,body:unknown){const r=await fetch(`https://api.telegram.org/bot${process.env.TELEGRAM_BOT_TOKEN}/${method}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body),signal:AbortSignal.timeout(7000)});const data=await r.json();if(!r.ok||!data.ok)throw Error('BOT_REQUEST_FAILED');}
export async function POST(request:NextRequest){const supplied=request.headers.get('X-Telegram-Bot-Api-Secret-Token')||'',secret=process.env.TELEGRAM_WEBHOOK_SECRET||'';if(!secret||Buffer.byteLength(secret)!==Buffer.byteLength(supplied)||!timingSafeEqual(Buffer.from(secret),Buffer.from(supplied)))return NextResponse.json({ok:false},{status:401});try{const u=await request.json();const db=database();if(u.pre_checkout_query){const q=u.pre_checkout_query;const{data:o}=await db.from('blu_coin_orders').select('*').eq('id',q.invoice_payload).maybeSingle();const valid=paymentsEnabled()&&o&&o.status==='pending'&&String(o.telegram_id)===String(q.from.id)&&q.currency==='XTR'&&q.total_amount===o.stars&&Date.now()-Date.parse(o.created_at)<86400000;await bot('answerPreCheckoutQuery',{pre_checkout_query_id:q.id,ok:!!valid,...(!valid?{error_message:'Order unavailable. Please reopen BLU CITY.'}:{})});}
const paid=u.message?.successful_payment;if(paid){const{error}=await db.rpc('blu_credit_coin_order',{p_id:paid.invoice_payload,p_user:String(u.message.from.id),p_currency:paid.currency,p_amount:paid.total_amount,p_charge:paid.telegram_payment_charge_id});if(error)throw Error('PAYMENT_CREDIT_FAILED');}
const msg=u.message?.text;if(typeof msg==='string'&&/^\/(paysupport|terms|start)/.test(msg)){const support=(process.env.BLU_SUPPORT_USERNAME||'BluCityGame_bot').replace(/^@/,'');await bot('sendMessage',{chat_id:u.message.chat.id,text:msg.startsWith('/terms')?'BLU CITY Coin are internal game credits with no cash value or withdrawal. Packs are one-time purchases. Coins arrive after Telegram confirms payment. For a purchase issue or refund request, send the payment receipt to @'+support:msg.startsWith('/paysupport')?'For purchase support or a refund request, send your payment receipt to @'+support:'Welcome to BLU CITY. Explore, restore the city and equip BLU.',reply_markup:{inline_keyboard:[[{text:'Play BLU CITY',web_app:{url:'https://blu-city-game.vercel.app/'}}]]}});}
return NextResponse.json({ok:true});}catch{return NextResponse.json({ok:false},{status:500});}}
